export const VOUCHER_FETCH_PROFILES = {
  minimal: [
    "GUID", "MASTERID", "ALTERID", "DATE", "VOUCHERTYPENAME", "VOUCHERNUMBER",
  ],
  accounting: [
    "*",
    "ALLLEDGERENTRIES.*",
    "LEDGERENTRIES.*",
    "ALLLEDGERENTRIES.BILLALLOCATIONS.*",
    "ALLLEDGERENTRIES.BANKALLOCATIONS.*",
  ],
  inventory: [
    "*",
    "ALLINVENTORYENTRIES.*",
    "ALLINVENTORYENTRIES.BATCHALLOCATIONS.*",
    "ALLINVENTORYENTRIES.ACCOUNTINGALLOCATIONS.*",
    "ALLINVENTORYENTRIES.RATEDETAILS.*",
  ],
  full: [
    "*",
    "ALLLEDGERENTRIES.*",
    "LEDGERENTRIES.*",
    "ALLLEDGERENTRIES.BILLALLOCATIONS.*",
    "ALLLEDGERENTRIES.BANKALLOCATIONS.*",
    "ALLLEDGERENTRIES.CATEGORYALLOCATIONS.*",
    "ALLLEDGERENTRIES.INVENTORYALLOCATIONS.*",
    "ALLINVENTORYENTRIES.*",
    "INVENTORYENTRIES.*",
    "ALLINVENTORYENTRIES.BATCHALLOCATIONS.*",
    "ALLINVENTORYENTRIES.ACCOUNTINGALLOCATIONS.*",
    "ALLINVENTORYENTRIES.RATEDETAILS.*",
  ],
} as const;
